language: android
sudo: true # travis-ci/travis-ci#5582 implies this could help against killed build-jobs
before_script:
    # update gradle
    - wget https://services.gradle.org/distributions/gradle-4.3-bin.zip
    - unzip -qq gradle-4.3-bin.zip
    - export GRADLE_HOME=$PWD/gradle-4.3
    - export PATH=$GRADLE_HOME/bin:$PATH
    - gradle -v
    - gradle dependencies || true
    - ./pre-build.sh
jdk: openjdk7
before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
android:
  components:
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
script: gradle build connectedCheck -PbuildServer
